### ISSUE TITLE
Nothing

### ISSUE THREAD

**Issue by dsk96m** [DevExpress-Examples/winforms-schedulercontrol-api-t224044#1]
Nothing shows up.  It is just a blank form.  I did a project converter to 18.1.4.
![image](https://user-images.githubusercontent.com/13119703/43271293-2424b10c-90c5-11e8-9ee8-36764f04455e.png)

**Comment by LexEPoX** [comment]
Hello.
This behavior occurs since GitHub replaces line endings in the sample files. We have fixed the issue so now, the sample works as expected.
